# Generated by Django 5.2.7 on 2025-11-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=300)),
                ("isbn", models.CharField(blank=True, max_length=13, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("non-fiction", "Non-Fiction"),
                            ("mystery", "Mystery"),
                            ("romance", "Romance"),
                            ("sci-fi", "Science Fiction"),
                            ("fantasy", "Fantasy"),
                            ("biography", "Biography"),
                            ("history", "History"),
                            ("self-help", "Self-Help"),
                            ("poetry", "Poetry"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("thriller", "Thriller"),
                            ("comedy", "Comedy"),
                            ("adventure", "Adventure"),
                            ("children", "Children"),
                            ("young-adult", "Young Adult"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="book_covers/"),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(default="English", max_length=50)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("book", "user")},
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
